"0","  ggplot(aes(x=value,fill=visit)) +"
"0","  geom_boxplot() +"
"0","  labs(title = str_c('Amount of diagnoses for people with 3 visits (',"
"0","                     diagnosis |>"
"0","                       select(-gender) |>"
"0","                       filter(if_all(c(-patient_nbr,-visit_1,-visit_2), is.na)) |>"
"0","                       filter(!if_all(c(visit_2),is.na)) |>"
"0","                       pull(patient_nbr) |>"
"0","                       length(),"
"0","                     ' people)'),"
"0","       x ='Number of diagnoses',"
"0","       fill = 'Visit number') "
"1","[1m[33mError[39m in `fortify()`:[22m
[38;5;232m[33m![38;5;232m `data` must be a [34m<data.frame>[38;5;232m, or an object coercible by
  `fortify()`, or a valid [34m<data.frame>[38;5;232m-like object coercible by
  `as.data.frame()`, not a <uneval> object.
[36mâ„¹[38;5;232m Did you accidentally pass `aes()` to the `data` argument?[39m
Backtrace:
[90m 1. [39mggplot2::ggplot(aes(x = value, fill = visit))
[90m 2. [39mggplot2:::ggplot.default(aes(x = value, fill = visit))
[90m 4. [39m[1m[94mggplot2:::fortify.default([39m[22mdata, ...[1m[94m)[39m[22m
"
